# Generated by Django 5.1.1 on 2024-10-05 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_category_title_anime'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anime',
            options={'verbose_name': 'аниме', 'verbose_name_plural': 'аниме'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категорию', 'verbose_name_plural': 'категории'},
        ),
        migrations.RemoveField(
            model_name='anime',
            name='category',
        ),
        migrations.AddField(
            model_name='anime',
            name='category',
            field=models.ManyToManyField(to='anime.category', verbose_name='Категория'),
        ),
    ]
