# Generated by Django 5.1.1 on 2024-10-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_alter_anime_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='release',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дата создания'),
        ),
    ]
