# Generated by Django 5.1.1 on 2024-10-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_ip_remove_anime_views_anime_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='video',
            field=models.FileField(blank=True, upload_to='video/', verbose_name='Видео'),
        ),
    ]
